const VEHICLE_LIST = [
    {
        brand: 'Hyundai',
        model: 'Avante',
        year: '2023',
        fuel: 'Gasoline',
        fuelEfficiency: '10.3km/l',
        cc: '1591cc',
        transmission: 'Automatic',
    },
    {
        brand: 'Hyundai',
        model: 'Casper',
        year: '2023',
        fuel: 'Gasoline',
        fuelEfficiency: '15.3km/l',
        cc: '998cc',
        transmission: 'Automatic',
    },
    {
        brand: 'Hyundai',
        model: 'G80',
        year: '2023',
        fuel: 'Gasoline',
        fuelEfficiency: '9.5km/l',
        cc: '2497cc',
        transmission: 'Automatic',
    },
    {
        brand: 'Hyundai',
        model: 'Grandeur',
        year: '2023',
        fuel: 'LPG',
        fuelEfficiency: '7.8km/l',
        cc: '3470cc',
        transmission: 'Automatic',
    },
    {
        brand: 'KIA',
        model: 'K9',
        year: '2023',
        fuel: 'Gasoline',
        fuelEfficiency: '9.0km/l',
        cc: '3778cc',
        transmission: 'Automatic',
    },
    {
        brand: 'KIA',
        model: 'Mohave',
        year: '2024',
        fuel: 'Diesel',
        fuelEfficiency: '9.3km/l',
        cc: '2959cc',
        transmission: 'Automatic',
    },
    {
        brand: 'KIA',
        model: 'Morning',
        year: '2023',
        fuel: 'Gasoline',
        fuelEfficiency: '15.7km/l',
        cc: '998cc',
        transmission: 'Automatic',
    },
    {
        brand: 'Hyundai',
        model: 'Palisade',
        year: '2023',
        fuel: 'Diesel',
        fuelEfficiency: '12.0km/l',
        cc: '2199cc',
        transmission: 'Automatic',
    },
];

export default VEHICLE_LIST;
