name: AWS_ACTION_CI_CD

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@main

            - name: Cache node modules
              uses: actions/cache@v1
              with:
                  path: node_moduels
                  key: ${{ runner.OS }}-main-build-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.OS }}-build-
                      ${{ runner.OS }}-

            - name: Install Dependencies # node module install
              run: yarn

            - name: Build
              run: yarn build:production

            - name: Deploy
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
              run: aws s3 sync ./build s3://blockmoters.shop
